language: node_js
node_js:
  - "12"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
before_script:
  - yarn global add codecov
script:
  - lerna run lint
  - lerna run test -- --coverage --updateSnapshot
  - codecov
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
